In [1]:
import numpy as np

In [3]:
#1-d array
x=np.array([5,6,7,8])
type(x)

numpy.ndarray

In [5]:
#2d array
x2=np.array([[1,2,3],[4,5,6]])
print(x2)

[[1 2 3]
 [4 5 6]]


In [14]:
#3d array
x3=np.array([[[1,2][3,4]],[[5,6],[7,8]]])
x3


<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
/var/folders/7x/hyffpnjs3ql7q2_ngpl2dmvc0000gn/T/ipykernel_14692/2800057570.py:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  x3=np.array([[[1,2][3,4]],[[5,6],[7,8]]])
/var/folders/7x/hyffpnjs3ql7q2_ngpl2dmvc0000gn/T/ipykernel_14692/2800057570.py:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  x3=np.array([[[1,2][3,4]],[[5,6],[7,8]]])
/var/folders/7x/hyffpnjs3ql7q2_ngpl2dmvc0000gn/T/ipykernel_14692/2800057570.py:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  x3=np.array([[[1,2][3,4]],[[5,6],[7,8]]])


TypeError: list indices must be integers or slices, not tuple

# for seeing what any function does use ? after function

# np.arange?

# what are dunder functions


In [13]:
#sequential matrix ,np.arange() and np.linspace()

np.arange(0,10,.2).reshape(5,10)
#reshape

array([[0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8],
       [2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8],
       [4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8],
       [6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8],
       [8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8]])

In [23]:

np.linspace(0,15,100).reshape(25,4)


array([[ 0.        ,  0.15151515,  0.3030303 ,  0.45454545],
       [ 0.60606061,  0.75757576,  0.90909091,  1.06060606],
       [ 1.21212121,  1.36363636,  1.51515152,  1.66666667],
       [ 1.81818182,  1.96969697,  2.12121212,  2.27272727],
       [ 2.42424242,  2.57575758,  2.72727273,  2.87878788],
       [ 3.03030303,  3.18181818,  3.33333333,  3.48484848],
       [ 3.63636364,  3.78787879,  3.93939394,  4.09090909],
       [ 4.24242424,  4.39393939,  4.54545455,  4.6969697 ],
       [ 4.84848485,  5.        ,  5.15151515,  5.3030303 ],
       [ 5.45454545,  5.60606061,  5.75757576,  5.90909091],
       [ 6.06060606,  6.21212121,  6.36363636,  6.51515152],
       [ 6.66666667,  6.81818182,  6.96969697,  7.12121212],
       [ 7.27272727,  7.42424242,  7.57575758,  7.72727273],
       [ 7.87878788,  8.03030303,  8.18181818,  8.33333333],
       [ 8.48484848,  8.63636364,  8.78787879,  8.93939394],
       [ 9.09090909,  9.24242424,  9.39393939,  9.54545455],
       [ 9.6969697 ,  9.

In [32]:
# randomize matrix with np.random
print(np.random.rand(4,4))

#np.random.radn() #normal distribution
print(np.random.randn(4,4))


#np.random.randint()
print(np.random.randint(-10,10,(4,4)))


#np.random.uniform()
print(np.random.uniform(0,2,(3,3))) # random float

#np.random.permutation()
print(np.random.permutation([1,2,3,4,5,6,7,8,9])) # random float





[[0.20040276 0.23742352 0.53865661 0.44074047]
 [0.35195007 0.15009261 0.12859901 0.88914269]
 [0.40907233 0.51340951 0.21358247 0.10454325]
 [0.25709534 0.03277405 0.12379541 0.09426999]]
[[ 0.781523    0.43096504  1.48308167 -0.32207128]
 [-0.34187091 -1.87456669 -1.2712372  -1.22232406]
 [ 0.77844146  1.01277054 -1.62927233  0.57442086]
 [-1.64816429 -0.13162396 -0.57999108 -2.39130139]]
[[ -8   8   8  -1]
 [ -8  -9   8 -10]
 [ -1   5  -5  -7]
 [ -6   1   4   9]]
[[0.06465339 0.61653521 1.13950679]
 [0.69728559 1.09709149 0.33523427]
 [0.07332658 0.09069144 0.11342695]]
[4 1 9 3 8 7 6 2 5]


In [33]:
xp=np.random.uniform(0,10,(4,4))
print(xp.astype(int))

[[4 7 8 4]
 [8 7 0 1]
 [5 5 1 1]
 [1 0 7 4]]


# operations


In [37]:
a=np.random.randint(-10,10,(3,3))
b=np.random.randint(-10,10,(3,3))
print(a)
print(b)


[[ 6  0 -3]
 [-4 -5 -8]
 [ 3 -7  0]]
[[ 3  9 -9]
 [ 5  8 -4]
 [-8  4 -1]]


In [46]:
#matrix and constant operations 
a * 10
a /10


array([[ 0.6,  0. , -0.3],
       [-0.4, -0.5, -0.8],
       [ 0.3, -0.7,  0. ]])

In [45]:
#same size matrix operations
print(a + b)
print(a  - b)
print(a / b)

[[  9   9 -12]
 [  1   3 -12]
 [ -5  -3  -1]]
[[  3  -9   6]
 [ -9 -13  -4]
 [ 11 -11   1]]
[[ 2.          0.          0.33333333]
 [-0.8        -0.625       2.        ]
 [-0.375      -1.75       -0.        ]]


In [44]:
#matrix multiplications
np.matmul(a,b) #or np.dot(a,b)or a @ b

array([[  42,   42,  -51],
       [  27, -108,   64],
       [ -26,  -29,    1]])