In [50]:

import numpy as np

In [51]:
    # Write a NumPy program to create an array of 10 zeros.
a=np.zeros(10)
a.shape

(10,)

In [52]:
    # Write a NumPy program to create an array of 10 ones
a=np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [53]:
# Write a NumPy program to create a 3x3 matrix with values ranging from 0 to 8.
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [54]:
# Write a NumPy program to reverse an array (first element becomes the last).
a=np.array([1,2,3,4,5,56])
rev=a[::-1]
rev




array([56,  5,  4,  3,  2,  1])

In [55]:
# Write a NumPy program to extract all odd numbers from an array.
a=np.arange(1,10)
odd=a[a%2!=0]
odd

array([1, 3, 5, 7, 9])

In [56]:
# Write a NumPy program to compute the sum of all elements, mean, and standard deviation of a given array.
a=np.arange(1,20)
sum=a.sum()
print(f'sum {sum}')
print(f'mean { a.mean()}')
print(f'Standard deviation {a.std()}')

sum 190
mean 10.0
Standard deviation 5.477225575051661


In [68]:
# Write a NumPy program to create a 5x5 matrix with random values and find the minimum and maximum values.
a=np.random.randint(1,10,(5,5))
print(a)
print(a.max())
print(a.min())

[[3 6 7 1 5]
 [6 5 2 8 2]
 [9 8 2 8 4]
 [6 1 5 6 5]
 [7 6 6 2 8]]
9
1


In [70]:
# Write a NumPy program to multiply two given matrices.
a=np.arange(1,10,5)
b=np.arange(1,10,5)
